---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - common

- hosts: master
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - master

- hosts: workers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - worker

- hosts: proxy_client
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - haproxy

- hosts: master
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - after_install